#ifndef INC_CONFIGURATION_H_
#define INC_CONFIGURATION_H_

#define MAX_SLAVE_SLOTS       2U
#define SLAVE_SLOT_ADDRS      { 0x01U, 0x02U}
#define MAX_SENSORS_PER_SLAVE 8U

#define RS485_BAUDRATE        115200U
#define RS485_DE_PORT         GPIOA
#define RS485_DE_PIN          GPIO_PIN_4
#define RS485_RX_FRAME_QUEUE_SIZE   8U
#define RS485_TX_FRAME_QUEUE_SIZE   4U

#define PROTO_RETRY_MAX					3U
#define PROTO_TIMEOUT_MS				500U
#define PROTO_TASK_IDLE_MS				10U
#define PROTO_TXCMD_QUEUE_SIZE			8U
#define PROTO_VALID_FRAME_QUEUE_SIZE	8U

#define DEVMGR_POLL_INTERVAL_MS   500U
#define DEVMGR_OFFLINE_THRESHOLD  5U
#define DEVMGR_LOOP_MS            5U
#define DEVMGR_TIMOUT_MS		  5000U

#define PRIO_PROTOCOL   6
#define PRIO_DEVMGR     5
#define PRIO_LCD        4
#define PRIO_BUTTON     3

#define STACK_PROTOCOL  1024U
#define STACK_DEVMGR    1024U
#define STACK_LCD       1024U
#define STACK_BUTTON    256U

#define LCD_I2C_ADDR     0x27U
#define LCD_COLS         16U
#define LCD_ROWS         2U
#define LCD_REFRESH_MS   200U

#define BTN_POLL_MS        10U
#define BTN_DEBOUNCE_MS    30U
#define BTN_LONG_PRESS_MS  800U
#define BTN_QUEUE_SIZE     8U

#endif /* INC_CONFIGURATION_H_ */
